#spring.application.name=heima-ai
spring:
  application:
    name: heima-ai
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:7b
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: qwen-max-latest
      embedding:
        options:
          model: text-embedding-v4




  datasource:
    url: jdbc:mysql://localhost:3306/ai?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: ai
    username: root
    password: 1234
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.heima.ai: debug
